### ISSUE TITLE
[QG 4] Clarify Chart testing

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/digital-product-pass#122]
## Description

Looking at the runs for [Lint and Test Charts](https://github.com/eclipse-tractusx/digital-product-pass/actions/workflows/helm-test.yaml), you can see, that all of the runs are failing. The only successful runs skip "Run chart-testing" and "Run helm upgrade".

Looking at the workflow itself, I can also see some [copy/paste of PVC manifests](https://github.com/eclipse-tractusx/digital-product-pass/actions/runs/5865294840/workflow#L125-L127) that I cannot see a reason for.

Also, wenn installing the latest Chart (version `1.0.0`), it's running in a crash loop. Installed via:

```shell
helm install dpp tractusx-dev/digital-product-pass --version 1.0.0 --namespace dpp --create-namespace
```

Results in a couple of restarts, but ending in Errors containing this hing:

```text
 [The following configuration properties have incompatible values: [[org.eclipse.tractusx.productpass.services.DataTransferService.checkEdcConsumerConnection]
```

If this is a malformed sample value, I think the default should be replace by a correctly formatted value. If it is a startup check, that could also be done on runtime (reachability test of remote service), then I would suggest to change this test to a runtime evaluation. The [TRG 5.01 Description](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01#description) does point out, that Charts should be installable without any config and at least start without issues.

This should be clarified, before the QG 4 check #108  is marked as passed

**Comment by matbmoser** [comment]
Hi @SebastianBezold,
We have some security requirements that states that we should check if the application is able to connect to its EDC consumer.

If the application is not able to reach the configured URL it will not initiate since it will not be able to work.

By adding this to false it would start without a problem but not work.
https://github.com/eclipse-tractusx/digital-product-pass/blob/cdccd4f2f0ee56445f8ef7771c0fc5b9440cb417/charts/digital-product-pass/values.yaml#L141-L145

I hope this was enough. What I can do is to recreate the release v1.0.0 just setting to false the `values.yaml` security definitions.

**Comment by matbmoser** [comment]
Hi @SebastianBezold,

We basically used the workflow provided by the TRGs.
We added security checks so that our backend application can run. We are able to deploy the application but if you dont configure any value and not have a valid EDC configuration the backend will not be useful. Is deployable but not useful.

The EDC consumer should be working and we check for this if the configuration is correct. 
And in the configuration we add a dummy edc url.

**Comment by matbmoser** [comment]
About the PVC:

For running the Container in the Github workflows we need a PV instance. Therefore we copy and paste the PV inside the workflow file system to enable it to work. If you would run it in local or in another environment the PV would not be needed.

**Comment by SebastianBezold** [comment]
Hi @matbmoser,

the original issue seems to be fixed, but the app is still not starting due to other startup config evaluation it seems:

run via:

```shell
install dpp tractusx-dev/digital-product-pass --version 1.0.0-rc3 --namespace dpp --create-namespace
```

Error:

```text
org.eclipse.tractusx.productpass.exceptions.ServiceException: [org.eclipse.tractusx.productpass.services.CatenaXService.start] It was not possible to get the discovery endpoints, [org.eclipse.tractusx.productpass.services.CatenaXService.getDiscoveryEndpoints] It was not possible to retrieve the discovery finder!, [org.eclipse.tractusx.productpass.services.AuthenticationService.getToken] It was not possible to retrieve the token!, [utils.HttpUtil] It was not possible to do POST request to https://<keycloak.url>/auth/realms/<realm>/protocol/openid-connect/token, Could not create URI object: Illegal character in authority at index 8: https://<keycloak.url>/auth/realms/%3Crealm%3E/protocol/openid-connect/token
```

**Comment by matbmoser** [comment]
Ok @SebastianBezold the issue with the dash tool has been resolved and the images have been published.

The new v1.0.0 version created from the release candidate rc4 contains the fix for this issue.

**Comment by SebastianBezold** [comment]
`1.0.0-rc4` and `1.0.0` running fine now
